# Arquivo principal para Docker Compose
# Define os serviços básicos para o projeto
# Este arquivo é usado como base para desenvolvimento e produção

version: '3.8'
services:
  db:
    image: postgres:16
    container_name: pokedex-db
    environment:
      POSTGRES_DB: pokedex
      POSTGRES_USER: pokedex
      POSTGRES_PASSWORD: pokedex
    ports:
      - "5432:5432"
    volumes:
      - ./docker/db/schema.sql:/docker-entrypoint-initdb.d/01_schema.sql

  pokedex-mobile-bff:
    build: .
    image: pokedex-mobile-bff
    container_name: pokedex-mobile-bff
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/pokedex
      SPRING_DATASOURCE_USERNAME: pokedex
      SPRING_DATASOURCE_PASSWORD: pokedex
    depends_on:
      - db
    ports:
      - "8080:8080"
